Repository rapyuta-robotics/alica, pull requests merged in 2022-11, with the labels that each got.

#346 Added test compilation logic
  alica_solver_interface/CMakeLists.txt
  alica_tests/CMakeLists.txt
  supplementary/alica_ros_proxy/CMakeLists.txt
  supplementary/autodiff/CMakeLists.txt
  supplementary/constraintsolver/CMakeLists.txt
  supplementary/supplementary_tests/CMakeLists.txt
Labels: Fixed

#341 Use github actions for both ros1 and ros2
  .github/workflows/coverity.yml
  .github/workflows/main.yml
  .github/workflows/ros1_build_test/Dockerfile
  .github/workflows/ros2_build_test/Dockerfile
  .github/workflows/ros2_build_test/entrypoint.sh
  .travis.yml
  check_clang_format.sh
  format_cpp.sh
  pre-commit
  travis_scripts/before_script.sh
Labels: No changelog

#347 fix path problem on dynamicloading and githubaction
  .github/workflows/main.yml
  alica_dynamic_loading/include/DynamicLoadingUtils.h
  alica_dynamic_loading/src/DynamicLoadingUtils.cpp
  supplementary/supplementary_tests/src/test/test_alica_dynamicloadcreator.cpp
Labels: Fixed

#350 Remove WorldModel as a singleton in turtlesim demo
  supplementary/alica_ros_turtlesim/alica/Expr/src/Go2RandomPosition.cpp
  supplementary/alica_ros_turtlesim/alica/Expr/src/GoTo.cpp
  supplementary/alica_ros_turtlesim/alica/Expr/src/conditions/conditions.cpp
  supplementary/alica_ros_turtlesim/alica_turtlesim_library/include/world_model.hpp
  supplementary/alica_ros_turtlesim/alica_turtlesim_library/src/Go2RandomPosition.cpp
  supplementary/alica_ros_turtlesim/alica_turtlesim_library/src/GoTo.cpp
  supplementary/alica_ros_turtlesim/alica_turtlesim_library/src/conditions.cpp
  supplementary/alica_ros_turtlesim/alica_turtlesim_library/src/world_model.cpp
  supplementary/alica_ros_turtlesim/include/alica_ros_turtlesim/base.hpp
  supplementary/alica_ros_turtlesim/include/alica_ros_turtlesim/world_model.hpp
  supplementary/alica_ros_turtlesim/src/base.cpp
  supplementary/alica_ros_turtlesim/src/base_node.cpp
  supplementary/alica_ros_turtlesim/src/world_model.cpp
Labels: Refactored
