Repository rapyuta-robotics/alica, pull requests merged in 2022-12, with the labels that each got.

#357 Test catkin install mode in CI
  .github/workflows/coverity.yml
  .github/workflows/ros1_build_test/Dockerfile
Labels: No changelog

#356 Fix dummy tracing in test
  alica_dummy_proxy/src/communication/AlicaDummyCommunication.cpp
  supplementary/alica_ros1/alica_tests/include/test_alica.h
  supplementary/alica_ros1/alica_tests/src/test/test_alica_logger.cpp
Labels: Fixed

#349 Fix test step until
  alica_test_utility/CMakeLists.txt
  alica_test_utility/include/alica/test/CounterClass.h
  alica_test_utility/include/alica/test/Util.h
  alica_test_utility/src/CounterClass.cpp
  supplementary/alica_ros1/alica_tests/CMakeLists.txt
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/Behaviour/CountIndefinitely.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/Behaviour/EmptyBehaviour.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/Configurations/ConfigurationTestPlan1588060981661.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/SchedulingTestMasterPlan1613378382024.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/SchedulingTestPlan11613378406860.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/SchedulingTestPlan21613378423610.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/SchedulingTestPlan31613378433623.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/SchedulingTestSequencePlan11614963946725.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/SimpleTestPlan1412252439925.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/conditions/conditions.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/constraints/ConstraintTestPlan1414068524245Constraints.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_alica_authority.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_alica_condition_plan.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_alica_condition_plantype.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_alica_scheduling.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_alica_simple_plan.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_alica_tracing.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_back_forth.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_beh_frequency.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_failure_handling.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_success_spam.cpp
  supplementary/alica_ros1/supplementary_tests/src/test/test_alica_problem_composition.cpp
  supplementary/alica_ros1/supplementary_tests/src/test/test_variable_handling.cpp
Labels: Improved

#362 Fix for warnings
  alica_engine/include/engine/IAlicaCommunication.h
  supplementary/alica_ros1/alica_ros_proxy/include/clock/AlicaRosTimer.h
Labels: No changelog

#367 Fix code generation for conditions
  alica_dynamic_loading/include/DynamicConditionCreator.h
  alica_dynamic_loading/include/DynamicTransitionConditionCreator.h
  alica_dynamic_loading/src/DynamicConditionCreator.cpp
  alica_dynamic_loading/src/DynamicTransitionConditionCreator.cpp
  alica_engine/include/engine/IConditionCreator.h
  alica_engine/include/engine/ITransitionConditionCreator.h
  alica_engine/src/engine/AlicaEngine.cpp
  alica_engine/src/engine/expressionhandler/ExpressionHandler.cpp
  supplementary/alica_codegeneration/alica-plan-designer-fx-codegeneration/src/main/java/de/unikassel/vs/alica/generator/cpp/XtendTemplates.xtend
  supplementary/alica_codegeneration/codegen/PlanDesignerFX-Codegeneration-0.1.1.1399.jar
  supplementary/alica_codegeneration/codegen/PlanDesignerFX-Codegeneration-0.1.1.1400.jar
  supplementary/alica_codegeneration/codegen/plugins/alica-plan-designer-fx-default-plugin-0.1.1-SNAPSHOT.jar
  supplementary/alica_ros1/alica_ros_turtlesim/Expr/include/alica/ConditionCreator.h
  supplementary/alica_ros1/alica_ros_turtlesim/Expr/include/alica/TransitionConditionCreator.h
  supplementary/alica_ros1/alica_ros_turtlesim/Expr/src/ConditionCreator.cpp
  supplementary/alica_ros1/alica_ros_turtlesim/Expr/src/TransitionConditionCreator.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/include/alica_tests/ConditionCreator.h
  supplementary/alica_ros1/alica_tests/src/test/Expr/include/alica_tests/TransitionConditionCreator.h
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/ConditionCreator.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/TransitionConditionCreator.cpp
  supplementary/alica_ros1/supplementary_tests/src/test/Expr/include/supplementary_tests/Behaviour/waitbehaviour.h
  supplementary/alica_ros1/supplementary_tests/src/test/Expr/include/supplementary_tests/Behaviour/waitbehaviour1234.h
  supplementary/alica_ros1/supplementary_tests/src/test/Expr/include/supplementary_tests/ConditionCreator.h
  supplementary/alica_ros1/supplementary_tests/src/test/Expr/include/supplementary_tests/TransitionConditionCreator.h
  supplementary/alica_ros1/supplementary_tests/src/test/Expr/src/Behaviour/waitbehaviour.cpp
  supplementary/alica_ros1/supplementary_tests/src/test/Expr/src/Behaviour/waitbehaviour1234.cpp
  supplementary/alica_ros1/supplementary_tests/src/test/Expr/src/BehaviourCreator.cpp
  supplementary/alica_ros1/supplementary_tests/src/test/Expr/src/ConditionCreator.cpp
  supplementary/alica_ros1/supplementary_tests/src/test/Expr/src/TransitionConditionCreator.cpp
  supplementary/alica_ros1/supplementary_tests/src/test/test_alica_dynamicloadcreator.cpp
  supplementary/alica_ros2/alica_ros2_turtlesim/Expr/include/alica/ConditionCreator.h
  supplementary/alica_ros2/alica_ros2_turtlesim/Expr/include/alica/TransitionConditionCreator.h
  supplementary/alica_ros2/alica_ros2_turtlesim/Expr/src/ConditionCreator.cpp
  supplementary/alica_ros2/alica_ros2_turtlesim/Expr/src/TransitionConditionCreator.cpp
Labels: Fixed

#359 Traces tag time when closed
  supplementary/alica_tracing/src/tracing/Trace.cpp
Labels: Improved

#368 Fix more unused parameter warnings
  alica_engine/include/engine/BasicPlan.h
  alica_engine/include/engine/IAlicaCommunication.h
  supplementary/alica_ros_proxy/include/clock/AlicaRosTimer.h
Labels: Fixed

#369 Fix dynamic loading in supplementary
  supplementary/alica_ros1/supplementary_tests/alica_supplementary_test_library/etc/plans/AcmePlan.pml
  supplementary/alica_ros1/supplementary_tests/alica_supplementary_test_library/etc/plans/behaviours/AcmeBeh.beh
  supplementary/alica_ros1/supplementary_tests/alica_supplementary_test_library/etc/plans/behaviours/WaitBehaviour.beh
  supplementary/alica_ros1/supplementary_tests/alica_supplementary_test_library/etc/plans/conditions/ConditionRepository.cnd
  supplementary/alica_ros1/supplementary_tests/alica_supplementary_test_library/include/AcmeBehaviour.h
  supplementary/alica_ros1/supplementary_tests/alica_supplementary_test_library/include/AcmePlan.h
  supplementary/alica_ros1/supplementary_tests/alica_supplementary_test_library/include/WaitBehaviour.h
  supplementary/alica_ros1/supplementary_tests/src/test/Expr/include/supplementary_tests/Behaviour/waitbehaviour.h
  supplementary/alica_ros1/supplementary_tests/src/test/Expr/include/supplementary_tests/Behaviour/waitbehaviour1234.h
  supplementary/alica_ros1/supplementary_tests/src/test/Expr/src/Behaviour/waitbehaviour.cpp
  supplementary/alica_ros1/supplementary_tests/src/test/Expr/src/Behaviour/waitbehaviour1234.cpp
  supplementary/alica_ros1/supplementary_tests/src/test/Expr/src/BehaviourCreator.cpp
  supplementary/alica_ros1/supplementary_tests/src/test/Expr/src/ConditionCreator.cpp
  supplementary/alica_ros1/supplementary_tests/src/test/etc/plans/Acme.pml
  supplementary/alica_ros1/supplementary_tests/src/test/etc/plans/behaviours/WaitBehaviour.beh
  supplementary/alica_ros1/supplementary_tests/src/test/etc/plans/conditions/AcmeRuntimeCondition.cnd
  supplementary/alica_ros1/supplementary_tests/src/test/etc/plans/conditions/AcmeTransitionCondition.cnd
  supplementary/alica_ros1/supplementary_tests/src/test/test_alica_dynamicloadcreator.cpp
  supplementary/alica_ros1/supplementary_tests/test/supplementary_tests.test
Labels: Fixed

#364 Fix warnings from Wextra and Wpedantic
  alica_engine/include/engine/AlicaEngine.h
  alica_engine/src/engine/ConfigChangeListener.cpp
  alica_engine/src/engine/TeamObserver.cpp
  cmake_flags/cflags.cmake
  supplementary/alica_ros1/supplementary_tests/alica_supplementary_test_library/include/AcmeBehaviour.h
  supplementary/alica_ros1/supplementary_tests/alica_supplementary_test_library/include/AcmePlan.h
  supplementary/alica_tracing/src/tracing/TraceFactory.cpp
Labels: Refactored

#371 Remove plan conversion tool
  supplementary/plan-conversion-tool/Readme.md
  supplementary/plan-conversion-tool/ShortReadme.md
  supplementary/plan-conversion-tool/img/Convert*.png
  supplementary/plan-conversion-tool/img/Folders.png
  supplementary/plan-conversion-tool/img/Maven-Menu.png
  supplementary/plan-conversion-tool/img/Run-Dialogue.png
  supplementary/plan-conversion-tool/img/Work-Directories.png
  supplementary/plan-conversion-tool/pom.xml
  supplementary/plan-conversion-tool/src/main/java/com/rapyutarobotics/alica/ConversionProcess.java
  supplementary/plan-conversion-tool/src/main/java/com/rapyutarobotics/alica/ConversionTool.java
  supplementary/plan-conversion-tool/src/main/java/com/rapyutarobotics/alica/ReferenceCollection.java
  supplementary/plan-conversion-tool/src/main/java/com/rapyutarobotics/alica/Tags.java
  supplementary/plan-conversion-tool/src/main/java/com/rapyutarobotics/alica/factories/AbstractPlanFactory.java
  supplementary/plan-conversion-tool/src/main/java/com/rapyutarobotics/alica/factories/AnnotatedPlanFactory.java
  supplementary/plan-conversion-tool/src/main/java/com/rapyutarobotics/alica/factories/BehaviourFactory.java
  supplementary/plan-conversion-tool/src/main/java/com/rapyutarobotics/alica/factories/ConditionFactory.java
  supplementary/plan-conversion-tool/src/main/java/com/rapyutarobotics/alica/factories/ConfAbstractPlanWrapperFactory.java
  supplementary/plan-conversion-tool/src/main/java/com/rapyutarobotics/alica/factories/ConfigurationFactory.java
  supplementary/plan-conversion-tool/src/main/java/com/rapyutarobotics/alica/factories/EntryPointFactory.java
  supplementary/plan-conversion-tool/src/main/java/com/rapyutarobotics/alica/factories/Factory.java
  supplementary/plan-conversion-tool/src/main/java/com/rapyutarobotics/alica/factories/PlanFactory.java
  supplementary/plan-conversion-tool/src/main/java/com/rapyutarobotics/alica/factories/PlanTypeFactory.java
  supplementary/plan-conversion-tool/src/main/java/com/rapyutarobotics/alica/factories/PostConditionFactory.java
  supplementary/plan-conversion-tool/src/main/java/com/rapyutarobotics/alica/factories/PreConditionFactory.java
  supplementary/plan-conversion-tool/src/main/java/com/rapyutarobotics/alica/factories/QuantifierFactory.java
  supplementary/plan-conversion-tool/src/main/java/com/rapyutarobotics/alica/factories/RoleFactory.java
  supplementary/plan-conversion-tool/src/main/java/com/rapyutarobotics/alica/factories/RoleSetFactory.java
  supplementary/plan-conversion-tool/src/main/java/com/rapyutarobotics/alica/factories/RuntimeConditionFactory.java
  supplementary/plan-conversion-tool/src/main/java/com/rapyutarobotics/alica/factories/StateFactory.java
  supplementary/plan-conversion-tool/src/main/java/com/rapyutarobotics/alica/factories/SynchronisationFactory.java
  supplementary/plan-conversion-tool/src/main/java/com/rapyutarobotics/alica/factories/TaskFactory.java
  supplementary/plan-conversion-tool/src/main/java/com/rapyutarobotics/alica/factories/TaskRepositoryFactory.java
  supplementary/plan-conversion-tool/src/main/java/com/rapyutarobotics/alica/factories/TerminalStateFactory.java
  supplementary/plan-conversion-tool/src/main/java/com/rapyutarobotics/alica/factories/TransitionFactory.java
  supplementary/plan-conversion-tool/src/main/java/com/rapyutarobotics/alica/factories/VariableBindingFactory.java
  supplementary/plan-conversion-tool/src/main/java/com/rapyutarobotics/alica/factories/VariableFactory.java
Labels: No changelog

#374 Migrate to quay.io
  dependencies.rosinstall
  supplementary/alica_designer_runtime/docker-compose.yml
Labels: No changelog
