Repository rapyuta-robotics/alica, pull requests merged in 2022-10, with the labels that each got.

#334 Add precommit and auto changelog info
  .github/release.yml
  .github/workflows/pre-commit.yml
  .github/workflows/require-labels.yml
  .pre-commit-config.yaml
  README.md
  docs/articles/constraints.md
  supplementary/plan-conversion-tool/Readme.md
  supplementary/plan-conversion-tool/ShortReadme.md
Labels: No changelog

#337 Removed ROS1 and Boost dependencies from tracing and constraintsolver packages
  alica_engine/include/engine/AlicaClock.h
  alica_engine/include/engine/allocationauthority/EntryPointRobotPair.h
  alica_simple_solver/CMakeLists.txt
  alica_solver_interface/CMakeLists.txt
  alica_tests/CMakeLists.txt
  supplementary/alica_ros_proxy/CMakeLists.txt
  supplementary/alica_ros_turtlesim/CMakeLists.txt
  supplementary/alica_tracing/CMakeLists.txt
  supplementary/alica_tracing/alica_tracingConfig.cmake.in
  supplementary/alica_tracing/package.xml
  supplementary/alica_tracing/src/tracing/TraceFactory.cpp
  supplementary/autodiff/CMakeLists.txt
  supplementary/constraintsolver/CMakeLists.txt
  supplementary/constraintsolver/constraintsolverConfig.cmake.in
  supplementary/constraintsolver/package.xml
  supplementary/constraintsolver/test/test_cnsat.cpp
  supplementary/constraintsolver/test/test_constraintsolver.cpp
  supplementary/supplementary_tests/CMakeLists.txt
Labels: Improved

#335 Added ROS2 Github action
  .github/workflows/main.yml
  .github/workflows/ros2_build_test/Dockerfile
  .github/workflows/ros2_build_test/entrypoint.sh
Labels: No changelog

#336 Removed Redundant cmake Libraries
  alica_common_config/CMakeLists.txt
  alica_common_config/alica_common_configConfig.cmake.in
  alica_common_config/include/alica_common_config/common_defines.h
  alica_common_config/package.xml
  alica_dummy_proxy/CMakeLists.txt
  alica_dummy_proxy/package.xml
  alica_engine/CMakeLists.txt
  alica_engine/include/engine/FileSystem.h
  alica_engine/package.xml
  alica_engine/src/engine/AlicaContext.cpp
  alica_engine/src/engine/FileSystem.cpp
  alica_engine/src/engine/Logger.cpp
  alica_engine/src/engine/Logging.cpp
  alica_engine/src/engine/RunningPlan.cpp
  alica_engine/src/engine/modelmanagement/ModelManager.cpp
  alica_engine/src/engine/modelmanagement/factories/Factory.cpp
  alica_simple_solver/CMakeLists.txt
  alica_simple_solver/package.xml
  alica_solver_interface/CMakeLists.txt
  alica_solver_interface/include/alica_solver_interface/Interval.h
  alica_solver_interface/package.xml
  alica_test_utility/CMakeLists.txt
  alica_test_utility/package.xml
  alica_tests/CMakeLists.txt
  alica_tests/package.xml
  cmake_flags/cflags.cmake
  essentials/.editorconfig
  essentials/fsystem/CMakeLists.txt
  essentials/fsystem/fsystemConfig.cmake.in
  essentials/fsystem/package.xml
  supplementary/alica_dummy_tracing/CMakeLists.txt
  supplementary/alica_ros_proxy/CMakeLists.txt
  supplementary/alica_ros_proxy/package.xml
  supplementary/alica_ros_turtlesim/CMakeLists.txt
  supplementary/alica_ros_turtlesim/package.xml
  supplementary/alica_tracing/CMakeLists.txt
  supplementary/autodiff/CMakeLists.txt
  supplementary/autodiff/package.xml
  supplementary/constraintsolver/CMakeLists.txt
  supplementary/constraintsolver/package.xml
  supplementary/constraintsolver/test/test_cnsat.cpp
  supplementary/supplementary_tests/CMakeLists.txt
  supplementary/supplementary_tests/package.xml
Labels: Refactored
