Repository rapyuta-robotics/alica, pull requests merged in 2023-03, with the labels that each got.

#429 Add ability to find config files in multiple dirs
  alica_engine/include/engine/AlicaContext.h
  alica_engine/include/engine/logging/Logging.h
  alica_engine/include/engine/modelmanagement/ModelManager.h
  alica_engine/src/engine/AlicaContext.cpp
  alica_engine/src/engine/AlicaEngine.cpp
  alica_engine/src/engine/modelmanagement/ModelManager.cpp
  alica_engine/src/engine/modelmanagement/factories/Factory.cpp
  alica_test_utility/include/alica/test/TestContext.h
  alica_test_utility/src/TestContext.cpp
  supplementary/alica_ros1/alica_ros_turtlesim/etc/roles/Roleset.rst
  supplementary/alica_ros1/alica_ros_turtlesim/src/base.cpp
  supplementary/alica_ros1/alica_tests/include/test_alica.h
  supplementary/alica_ros1/alica_tests/src/test/test_alica_engine_plan_parser.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_assignment.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_success.cpp
  supplementary/alica_ros1/supplementary_tests/include/test_supplementary.h
  supplementary/alica_ros2/alica_ros2_turtlesim/etc/roles/Roleset.rst
  supplementary/alica_ros2/alica_ros2_turtlesim/src/base.cpp
Labels: Improved

#432 Refactor turtlesim and add additional simpler tutorial plan
  alica_standard_library/CMakeLists.txt
  alica_standard_library/include/Conditions.h
  alica_standard_library/include/GenerateRandom.h
  alica_standard_library/src/Conditions.cpp
  alica_standard_library/src/GenerateRandom.cpp
  supplementary/alica_ros1/alica_ros_turtlesim/etc/Alica.yaml
  supplementary/alica_ros1/alica_ros_turtlesim/etc/behaviours/GenerateRandom.beh
  supplementary/alica_ros1/alica_ros_turtlesim/etc/behaviours/GoTo.beh
  supplementary/alica_ros1/alica_ros_turtlesim/etc/behaviours/GoToCalculatedResult.beh
  supplementary/alica_ros1/alica_ros_turtlesim/etc/behaviours/Idle.beh
  supplementary/alica_ros1/alica_ros_turtlesim/etc/behaviours/SpawnTurtle.beh
  supplementary/alica_ros1/alica_ros_turtlesim/etc/behaviours/Teleport.beh
  supplementary/alica_ros1/alica_ros_turtlesim/etc/behaviours/WaitForTrigger.beh
  supplementary/alica_ros1/alica_ros_turtlesim/etc/conditions/ConditionRepository.cnd
  supplementary/alica_ros1/alica_ros_turtlesim/etc/plans/MakeFormation.pml
  supplementary/alica_ros1/alica_ros_turtlesim/etc/plans/RandomMoveTutorial.pml
  supplementary/alica_ros1/alica_ros_turtlesim/etc/plans/Simulation.pml
  supplementary/alica_ros1/alica_ros_turtlesim/etc/plans/SurroundLeaderTutorial.pml
  supplementary/alica_ros1/alica_ros_turtlesim/etc/plans/TeleportToRandomPosition.pml
  supplementary/alica_ros1/alica_ros_turtlesim/etc/plans/behaviours/Teleport2RandomPosition.beh
  supplementary/alica_ros1/alica_ros_turtlesim/launch/turtle.launch
  supplementary/alica_ros1/alica_ros_turtlesim/libalica-turtlesim/CMakeLists.txt
  supplementary/alica_ros1/alica_ros_turtlesim/libalica-turtlesim/include/GoTo.h
  supplementary/alica_ros1/alica_ros_turtlesim/libalica-turtlesim/include/GoToCalculatedResult.h
  supplementary/alica_ros1/alica_ros_turtlesim/libalica-turtlesim/include/Idle.h
  supplementary/alica_ros1/alica_ros_turtlesim/libalica-turtlesim/include/MakeFormation.h
  supplementary/alica_ros1/alica_ros_turtlesim/libalica-turtlesim/include/Master.h
  supplementary/alica_ros1/alica_ros_turtlesim/libalica-turtlesim/include/RandomMoveTutorial.h
  supplementary/alica_ros1/alica_ros_turtlesim/libalica-turtlesim/include/Simulation.h
  supplementary/alica_ros1/alica_ros_turtlesim/libalica-turtlesim/include/SpawnTurtle.h
  supplementary/alica_ros1/alica_ros_turtlesim/libalica-turtlesim/include/SurroundLeaderTutorial.h
  supplementary/alica_ros1/alica_ros_turtlesim/libalica-turtlesim/include/Teleport.h
  supplementary/alica_ros1/alica_ros_turtlesim/libalica-turtlesim/include/Teleport2RandomPosition.h
  supplementary/alica_ros1/alica_ros_turtlesim/libalica-turtlesim/include/TeleportToRandomPosition.h
  supplementary/alica_ros1/alica_ros_turtlesim/libalica-turtlesim/include/turtle_interfaces.hpp
  supplementary/alica_ros1/alica_ros_turtlesim/libalica-turtlesim/src/GoTo.cpp
  supplementary/alica_ros1/alica_ros_turtlesim/libalica-turtlesim/src/GoToCalculatedResult.cpp
  supplementary/alica_ros1/alica_ros_turtlesim/libalica-turtlesim/src/Idle.cpp
  supplementary/alica_ros1/alica_ros_turtlesim/libalica-turtlesim/src/MakeFormation.cpp
  supplementary/alica_ros1/alica_ros_turtlesim/libalica-turtlesim/src/Master.cpp
  supplementary/alica_ros1/alica_ros_turtlesim/libalica-turtlesim/src/RandomMoveTutorial.cpp
  supplementary/alica_ros1/alica_ros_turtlesim/libalica-turtlesim/src/Simulation.cpp
  supplementary/alica_ros1/alica_ros_turtlesim/libalica-turtlesim/src/SpawnTurtle.cpp
  supplementary/alica_ros1/alica_ros_turtlesim/libalica-turtlesim/src/SurroundLeaderTutorial.cpp
  supplementary/alica_ros1/alica_ros_turtlesim/libalica-turtlesim/src/Teleport.cpp
  supplementary/alica_ros1/alica_ros_turtlesim/libalica-turtlesim/src/Teleport2RandomPosition.cpp
  supplementary/alica_ros1/alica_ros_turtlesim/libalica-turtlesim/src/TeleportToRandomPosition.cpp
  supplementary/alica_ros1/alica_ros_turtlesim/libalica-turtlesim/src/turtle_interfaces.cpp
Labels: Improved

#447 Fix Alica tracing error marking
  supplementary/alica_tracing/src/tracing/Trace.cpp
Labels: Fixed

#449 Add backward compatible test context constructor for config path
  alica_test_utility/include/alica/test/TestContext.h
  alica_test_utility/src/TestContext.cpp
Labels: Fixed

#452 Fix roleset name to match rst file name
  supplementary/alica_ros1/alica_ros_turtlesim/etc/roles/Roleset.rst
  supplementary/alica_ros2/alica_ros2_turtlesim/etc/roles/Roleset.rst
Labels: Fixed

#459 Cleanup debug logs in constraint queries
  alica_engine/src/engine/constraintmodul/ConditionStore.cpp
  alica_engine/src/engine/constraintmodul/Query.cpp
Labels: Fixed

#455 Remove legacy transitions
  alica_engine/include/engine/model/Transition.h
  alica_engine/src/engine/AlicaEngine.cpp
  alica_engine/src/engine/model/Transition.cpp
  alica_engine/src/engine/modelmanagement/factories/TransitionFactory.cpp
  alica_tests/CMakeLists.txt
  alica_tests/include/test_alica.h
  alica_tests/src/test/test_legacy_conditions.cpp
  supplementary/alica_ros1/supplementary_tests/src/test/test_alica_dynamicloadcreator.cpp
Labels: Deprecated

#461 Fix warning
  supplementary/alica_ros1/alica_ros_proxy/include/logger/AlicaRosLogger.h
Labels: No changelog

#463 Add IsChildSuccess condition
  alica_standard_library/include/Conditions.h
  alica_standard_library/src/Conditions.cpp
  alica_tests/include/alica_tests/plans/IsChildSuccessTestPlan.h
  alica_tests/src/plans/IsChildSuccessTestPlan.cpp
  alica_tests/src/test/etc/conditions/ConditionRepository.cnd
  alica_tests/src/test/etc/plans/IsChildSuccessTestPlan.pml
  alica_tests/src/test/etc/plans/TestMasterPlan.pml
  alica_tests/src/test/test_success.cpp
Labels: Added

#466 Minor cleanup
  alica_tests/src/conditions/conditions.cpp
  alica_tests/src/plans/BlackboardTestPlan.cpp
Labels: Refactored

#467 Update version numbers to prepare for 1.0.0 tag
  .github/ISSUE_TEMPLATE/bug_report.md
  alica_dummy_proxy/CMakeLists.txt
  alica_dummy_proxy/package.xml
  alica_dynamic_loading/CMakeLists.txt
  alica_engine/CMakeLists.txt
  alica_engine/package.xml
  alica_engine/src/engine/AlicaContext.cpp
  alica_simple_solver/CMakeLists.txt
  alica_simple_solver/package.xml
  alica_solver_interface/CMakeLists.txt
  alica_solver_interface/package.xml
  alica_standard_library/CMakeLists.txt
  alica_standard_library/package.xml
  alica_test_utility/CMakeLists.txt
  alica_test_utility/package.xml
  alica_tests/CMakeLists.txt
  alica_tests/package.xml
  supplementary/alica_dummy_tracing/CMakeLists.txt
  supplementary/alica_dummy_tracing/package.xml
  supplementary/alica_msgs/package.xml
  supplementary/alica_ros1/alica_ros_proxy/package.xml
  supplementary/alica_ros1/alica_ros_turtlesim/package.xml
  supplementary/alica_ros1/supplementary_tests/package.xml
  supplementary/alica_ros2/alica_ros2_proxy/CMakeLists.txt
  supplementary/alica_ros2/alica_ros2_proxy/package.xml
  supplementary/alica_ros2/alica_ros2_turtlesim/package.xml
  supplementary/alica_tracing/CMakeLists.txt
  supplementary/alica_tracing/package.xml
  supplementary/constraintsolver/CMakeLists.txt
  supplementary/constraintsolver/package.xml
Labels: No changelog

#470 Allow taking tracing tags from env
  supplementary/alica_tracing/src/tracing/TraceFactory.cpp
Labels: Added

#473 Remove pluginName
  alica_engine/include/engine/modelmanagement/Strings.h
  alica_engine/src/engine/modelmanagement/factories/ConditionFactory.cpp
  alica_tests/src/test/test_alica_engine_plan_parser.cpp
Labels: Deprecated

#472 Remove master plan flag
  alica_engine/include/engine/BasicPlan.h
  alica_engine/include/engine/model/Plan.h
  alica_engine/include/engine/modelmanagement/Strings.h
  alica_engine/src/engine/BasicPlan.cpp
  alica_engine/src/engine/model/Plan.cpp
  alica_engine/src/engine/modelmanagement/factories/PlanFactory.cpp
  alica_tests/src/test/test_alica_engine_plan_parser.cpp
Labels: Deprecated

#469 Removing Configuration
  alica_engine/CMakeLists.txt
  alica_engine/include/engine/PlanBase.h
  alica_engine/include/engine/PlanRepository.h
  alica_engine/include/engine/RunningPlan.h
  alica_engine/include/engine/model/Configuration.h
  alica_engine/include/engine/modelmanagement/Strings.h
  alica_engine/include/engine/modelmanagement/factories/ConfigurationFactory.h
  alica_engine/include/engine/planselector/PlanSelector.h
  alica_engine/src/engine/BasicBehaviour.cpp
  alica_engine/src/engine/PlanBase.cpp
  alica_engine/src/engine/RuleBook.cpp
  alica_engine/src/engine/RunningPlan.cpp
  alica_engine/src/engine/model/Configuration.cpp
  alica_engine/src/engine/modelmanagement/ModelManager.cpp
  alica_engine/src/engine/modelmanagement/factories/ConfAbstractPlanWrapperFactory.cpp
  alica_engine/src/engine/modelmanagement/factories/ConfigurationFactory.cpp
  alica_engine/src/engine/modelmanagement/factories/Factory.cpp
  alica_engine/src/engine/planselector/PlanSelector.cpp
  alica_test_utility/src/TestContext.cpp
  alica_test_utility/src/Util.cpp
  alica_tests/include/alica_tests/conditions/conditions.h
  alica_tests/include/alica_tests/plans/Configurations/ConfigurationTestPlan.h
  alica_tests/include/alica_tests/plans/Configurations/ReadConfInPlantype.h
  alica_tests/include/alica_tests/plans/Configurations/ReadConfigurationPlan.h
  alica_tests/src/behaviours/ReadConfigurationBehaviour.cpp
  alica_tests/src/conditions/conditions.cpp
  alica_tests/src/plans/Configurations/ConfigurationTestPlan.cpp
  alica_tests/src/plans/Configurations/ReadConfInPlantype.cpp
  alica_tests/src/plans/Configurations/ReadConfigurationPlan.cpp
  alica_tests/src/test/etc/conditions/ConditionRepository.cnd
  alica_tests/src/test/etc/configurations/ConfigA.cfg
  alica_tests/src/test/etc/configurations/ConfigB.cfg
  alica_tests/src/test/etc/plans/ConfigurationTestPlan.pml
  alica_tests/src/test/etc/plans/ReadConfInPlantype.pml
  alica_tests/src/test/etc/plans/ReadConfigurationPlan.pml
  alica_tests/src/test/etc/plans/ReadConfigurationPlantype.pty
  alica_tests/src/test/test_task_assignment.cpp
Labels: Deprecated

#477 Improved error handling & tests in dynamic loading
  alica_dynamic_loading/include/DynamicLoadingUtils.h
  alica_dynamic_loading/src/DynamicBehaviourCreator.cpp
  alica_dynamic_loading/src/DynamicConditionCreator.cpp
  alica_dynamic_loading/src/DynamicConstraintCreator.cpp
  alica_dynamic_loading/src/DynamicLoadingUtils.cpp
  alica_dynamic_loading/src/DynamicPlanCreator.cpp
  alica_dynamic_loading/src/DynamicTransitionConditionCreator.cpp
  alica_dynamic_loading/src/DynamicUtilityFunctionCreator.cpp
  alica_engine/include/engine/Output.h
  alica_engine/include/engine/UtilityFunction.h
  alica_engine/include/engine/blackboard/Blackboard.h
  alica_tests/include/alica_tests/plans/ConstraintTestPlan.h
  alica_tests/include/alica_tests/plans/FailsOnOne.h
  alica_tests/include/alica_tests/plans/GoalPlan.h
  alica_tests/include/alica_tests/plans/MidFieldPlayPlan.h
  alica_tests/include/alica_tests/plans/PreConditionPlan.h
  alica_tests/include/alica_tests/plans/RuntimeConditionPlan.h
  alica_tests/include/alica_tests/plans/SimpleTestPlan.h
  supplementary/alica_ros1/supplementary_tests/libalica-supplementary-tests/include/libalica-supplementary-tests/AcmePlan.h
  supplementary/alica_ros1/supplementary_tests/libalica-supplementary-tests/include/libalica-supplementary-tests/GSolver/GSolverMaster.h
  supplementary/alica_ros1/supplementary_tests/libalica-supplementary-tests/include/libalica-supplementary-tests/GSolver/GSolverTestPlan.h
  supplementary/alica_ros1/supplementary_tests/libalica-supplementary-tests/include/libalica-supplementary-tests/ProblemModule/ProbBuildingLevel1.h
  supplementary/alica_ros1/supplementary_tests/libalica-supplementary-tests/include/libalica-supplementary-tests/ProblemModule/ProbBuildingLevel1_1.h
  supplementary/alica_ros1/supplementary_tests/libalica-supplementary-tests/include/libalica-supplementary-tests/ProblemModule/ProblemBuildingMaster.h
  supplementary/alica_ros1/supplementary_tests/libalica-supplementary-tests/include/libalica-supplementary-tests/ProblemModule/QueryPlan1.h
  supplementary/alica_ros1/supplementary_tests/libalica-supplementary-tests/include/libalica-supplementary-tests/ProblemModule/QueryPlan2.h
  supplementary/alica_ros1/supplementary_tests/libalica-supplementary-tests/include/libalica-supplementary-tests/VariableHandling/Lvl1.h
  supplementary/alica_ros1/supplementary_tests/libalica-supplementary-tests/include/libalica-supplementary-tests/VariableHandling/Lvl2.h
  supplementary/alica_ros1/supplementary_tests/libalica-supplementary-tests/include/libalica-supplementary-tests/VariableHandling/Lvl3.h
  supplementary/alica_ros1/supplementary_tests/libalica-supplementary-tests/include/libalica-supplementary-tests/VariableHandling/VHMaster.h
  supplementary/alica_ros1/supplementary_tests/libalica-supplementary-tests/src/libalica-supplementary-tests/GSolver/GSolverMaster.cpp
  supplementary/alica_ros1/supplementary_tests/libalica-supplementary-tests/src/libalica-supplementary-tests/GSolver/GSolverTestPlan.cpp
  supplementary/alica_ros1/supplementary_tests/libalica-supplementary-tests/src/libalica-supplementary-tests/ProblemModule/ProbBuildingLevel1.cpp
  supplementary/alica_ros1/supplementary_tests/libalica-supplementary-tests/src/libalica-supplementary-tests/ProblemModule/ProbBuildingLevel1_1.cpp
  supplementary/alica_ros1/supplementary_tests/libalica-supplementary-tests/src/libalica-supplementary-tests/ProblemModule/ProblemBuildingMaster.cpp
  supplementary/alica_ros1/supplementary_tests/libalica-supplementary-tests/src/libalica-supplementary-tests/ProblemModule/QueryPlan1.cpp
  supplementary/alica_ros1/supplementary_tests/libalica-supplementary-tests/src/libalica-supplementary-tests/ProblemModule/QueryPlan2.cpp
  supplementary/alica_ros1/supplementary_tests/libalica-supplementary-tests/src/libalica-supplementary-tests/VariableHandling/Lvl1.cpp
  supplementary/alica_ros1/supplementary_tests/libalica-supplementary-tests/src/libalica-supplementary-tests/VariableHandling/Lvl2.cpp
  supplementary/alica_ros1/supplementary_tests/libalica-supplementary-tests/src/libalica-supplementary-tests/VariableHandling/Lvl3.cpp
  supplementary/alica_ros1/supplementary_tests/libalica-supplementary-tests/src/libalica-supplementary-tests/VariableHandling/VHMaster.cpp
  supplementary/alica_ros1/supplementary_tests/src/test/test_alica_dynamicloadcreator.cpp
Labels: Improved
