Repository rapyuta-robotics/alica, pull requests merged in 2023-04, with the labels that each got.

#478 Comparator conditions in alica_standard_library
  alica_standard_library/include/Conditions.h
  alica_standard_library/src/Conditions.cpp
  alica_tests/CMakeLists.txt
  alica_tests/etc/conditions/ConditionRepository.cnd
  alica_tests/etc/plans/StandardLibraryCompareConditionsPlan.pml
  alica_tests/etc/plans/TestMasterPlan.pml
  alica_tests/include/alica_tests/plans/StandardLibraryCompareConditionsPlan.h
  alica_tests/src/plans/StandardLibraryCompareConditionsPlan.cpp
  alica_tests/src/test/test_standard_library_conditions.cpp
Labels: Added

#484 unsubscribe from config change listener on destruction of CycleManage…
  alica_engine/include/engine/ConfigChangeListener.h
  alica_engine/include/engine/allocationauthority/CycleManager.h
  alica_engine/src/engine/ConfigChangeListener.cpp
  alica_engine/src/engine/allocationauthority/CycleManager.cpp
  alica_tests/src/test/test_config_change.cpp
Labels: Fixed

#485 Remove configuration leftovers
  alica_engine/include/engine/model/ConfAbstractPlanWrapper.h
  alica_engine/include/engine/modelmanagement/factories/Factory.h
  alica_engine/src/engine/model/ConfAbstractPlanWrapper.cpp
  alica_engine/src/engine/modelmanagement/factories/ConfAbstractPlanWrapperFactory.cpp
  alica_engine/src/engine/modelmanagement/factories/Factory.cpp
  alica_test_utility/include/alica/test/Util.h
  alica_test_utility/src/Util.cpp
  alica_tests/src/test/test_alica_behaviourtrigger.cpp
  alica_tests/src/test/test_alica_condition_plan.cpp
  alica_tests/src/test/test_alica_multi_agent_plan.cpp
  alica_tests/src/test/test_alica_scheduling.cpp
  alica_tests/src/test/test_alica_simple_plan.cpp
  alica_tests/src/test/test_blackboard.cpp
  alica_tests/src/test/test_inherit_blackboard.cpp
Labels: Refactored

#479 Improve type determination in blackboard impl
  alica_engine/include/engine/blackboard/Blackboard.h
Labels: Improved

#488 Remove msgs of all deactivated agents
  alica_engine/include/engine/teammanager/TeamManager.h
  alica_engine/src/engine/TeamObserver.cpp
  alica_engine/src/engine/teammanager/TeamManager.cpp
Labels: Fixed
