Repository rapyuta-robotics/alica, pull requests merged in 2023-01, with the labels that each got.

#372 Allow using basic types in traces
  alica_engine/include/engine/IAlicaTrace.h
  supplementary/alica_tracing/include/tracing/Trace.h
  supplementary/alica_tracing/src/tracing/Trace.cpp
Labels: Improved

#377 Minor CMake bug in alica_tracing
  supplementary/alica_tracing/CMakeLists.txt
Labels: Fixed

#370 Remove deprecated docs
  docs/deprecated_doc/Alica_Base.md
  docs/deprecated_doc/Alica_alica_conf.md
  docs/deprecated_doc/Alica_autogen.md
  docs/deprecated_doc/Alica_globals_conf.md
  docs/deprecated_doc/Alica_howto_get_the_framework_running.md
  docs/deprecated_doc/Alica_howto_setup_your_eclipse.md
  docs/deprecated_doc/Domain.md
  docs/deprecated_doc/How-to-compile-and-install-yamlcpp.txt
  docs/deprecated_doc/PlanConstraintCode.md
  docs/deprecated_doc/PlanDesignerNewPlan.png
  docs/deprecated_doc/Plancode.md
Labels: No changelog

#379 Get rid of clang-format link
  .clang-format
  docs/style/clang-format
Labels: No changelog

#338 Add support for blackboard types
  alica_dummy_proxy/src/communication/AlicaDummyCommunication.cpp
  alica_engine/include/engine/Types.h
  alica_engine/include/engine/blackboard/Blackboard.h
  alica_engine/include/engine/blackboard/BlackboardBlueprint.h
  alica_engine/src/engine/blackboard/BlackboardUtil.cpp
  alica_engine/src/engine/modelmanagement/factories/BlackboardBlueprintFactory.cpp
  alica_simple_solver/src/SimpleSolver.cpp
  supplementary/alica_ros1/alica_tests/src/ConstraintTestPlanDummySolver.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/Behaviour/TestInheritBlackboardBehaviour.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/Behaviour/TestParameterPassingBehaviour.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/HandleFailExplicit1530004915640.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/SchedulingTestPlan11613378406860.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/SimpleTestPlan1412252439925.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/TestParameterPassing1692837668719979457.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/TestParameterPassingMaster1179066429431332055.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/conditions/conditions.cpp
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/ConfigurationTestPlan.pml
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/HandleFailExplicit.pml
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/SchedulingTestPlan1.pml
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/SchedulingTestSequencePlan1.pml
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/TestInheritBlackboardMaster.pml
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/TestParameterPassing.pml
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/TestParameterPassingMaster.pml
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/behaviours/TestParameterPassingBehaviour.beh
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/conditions/ConditionRepository.cnd
  supplementary/alica_ros1/alica_tests/src/test/test_alica_simple_plan.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_blackboard.cpp
  supplementary/alica_ros1/supplementary_tests/src/test/Expr/src/ConstraintTestPlanDummySolver.cpp
  supplementary/constraintsolver/src/CNSMTGSolver.cpp
  supplementary/constraintsolver/src/GSolver.cpp
Labels: Added

#381 Fix tracing alica tests
  supplementary/alica_ros1/alica_tests/include/alica_tests/TestTracing.h
Labels: Fixed

#365 Improve tests
  alica_engine/include/engine/blackboard/Blackboard.h
  alica_engine/include/engine/model/TransitionCondition.h
  alica_test_utility/CMakeLists.txt
  alica_test_utility/include/alica/test/TestContext.h
  alica_test_utility/include/alica/test/Util.h
  alica_test_utility/src/TestContext.cpp
  supplementary/alica_ros1/alica_tests/CMakeLists.txt
  supplementary/alica_ros1/alica_tests/include/alica_tests/TestWorldModel.h
  supplementary/alica_ros1/alica_tests/src/test/Expr/include/alica_tests/BehSuccessTestPlan2189867578804904568.h
  supplementary/alica_ros1/alica_tests/src/test/Expr/include/alica_tests/Behaviour/SuccessOnInitBeh.h
  supplementary/alica_ros1/alica_tests/src/test/Expr/include/alica_tests/Behaviour/SuccessOnInitBeh3821787310391665935.h
  supplementary/alica_ros1/alica_tests/src/test/Expr/include/alica_tests/MultiPlanInstanceSuccessTestPlan3392981108193862307.h
  supplementary/alica_ros1/alica_tests/src/test/Expr/include/alica_tests/ParallelSuccessOnCondPlan3288843407985944525.h
  supplementary/alica_ros1/alica_tests/src/test/Expr/include/alica_tests/PlanSuccessTestPlan3870436056558842479.h
  supplementary/alica_ros1/alica_tests/src/test/Expr/include/alica_tests/SuccessOnCondPlan3153116020668535682.h
  supplementary/alica_ros1/alica_tests/src/test/Expr/include/alica_tests/SuccessOnCondWrapperAPlan673160616613514188.h
  supplementary/alica_ros1/alica_tests/src/test/Expr/include/alica_tests/SuccessOnCondWrapperBPlan2869465844414224272.h
  supplementary/alica_ros1/alica_tests/src/test/Expr/include/alica_tests/SuccessOnInitPlan1863216812678266511.h
  supplementary/alica_ros1/alica_tests/src/test/Expr/include/alica_tests/TestMasterPlan2521443078354411465.h
  supplementary/alica_ros1/alica_tests/src/test/Expr/include/alica_tests/conditions/conditions.h
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/BehSuccessTestPlan2189867578804904568.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/Behaviour/SuccessOnInitBeh.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/Behaviour/SuccessOnInitBeh3821787310391665935.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/BehaviourCreator.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/ConditionCreator.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/LegacyTransitionConditionCreator.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/MultiPlanInstanceSuccessTestPlan3392981108193862307.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/ParallelSuccessOnCondPlan3288843407985944525.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/PlanCreator.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/PlanSuccessTestPlan3870436056558842479.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/SuccessOnCondPlan3153116020668535682.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/SuccessOnCondWrapperAPlan673160616613514188.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/SuccessOnCondWrapperBPlan2869465844414224272.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/SuccessOnInitPlan1863216812678266511.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/TestMasterPlan2521443078354411465.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/TransitionConditionCreator.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/UtilityFunctionCreator.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/conditions/conditions.cpp
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/BehSuccessTestPlan.pml
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/MultiPlanInstanceSuccessTestPlan.pml
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/ParallelSuccessOnCondPlan.pml
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/PlanSuccessTestPlan.pml
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/SuccessOnCondPlan.pml
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/SuccessOnCondWrapperAPlan.pml
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/SuccessOnCondWrapperBPlan.pml
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/SuccessOnInitPlan.pml
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/TestMasterPlan.pml
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/behaviours/SuccessOnInitBeh.beh
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/conditions/ConditionRepository.cnd
  supplementary/alica_ros1/alica_tests/src/test/test_blackboard.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_success.cpp
Labels: Improved

#382 Fix ci
  .github/workflows/ros1_build_test/Dockerfile
  .github/workflows/ros2_build_test/Dockerfile
Labels: Fixed

#383 Update implementation of DummyAlicaTracing
  supplementary/alica_dummy_tracing/include/alica_dummy_tracing/DummyAlicaTracing.h
Labels: Fixed

#378 Improve logs
  alica_dynamic_loading/src/DynamicLoadingUtils.cpp
  alica_engine/include/engine/AlicaContext.h
  alica_engine/include/engine/AlicaEngine.h
  alica_engine/include/engine/IRoleAssignment.h
  alica_engine/include/engine/Logger.h
  alica_engine/include/engine/PlanBase.h
  alica_engine/include/engine/RuleBook.h
  alica_engine/include/engine/RunnableObject.h
  alica_engine/include/engine/RunningPlan.h
  alica_engine/include/engine/TeamObserver.h
  alica_engine/include/engine/allocationauthority/CycleManager.h
  alica_engine/include/engine/constraintmodul/Query.h
  alica_engine/include/engine/constraintmodul/VariableSyncModule.h
  alica_engine/include/engine/modelmanagement/ModelManager.h
  alica_engine/include/engine/modelmanagement/factories/Factory.h
  alica_engine/include/engine/planselector/PlanSelector.h
  alica_engine/include/engine/teammanager/TeamManager.h
  alica_engine/src/engine/AlicaContext.cpp
  alica_engine/src/engine/AlicaEngine.cpp
  alica_engine/src/engine/BasicBehaviour.cpp
  alica_engine/src/engine/BasicPlan.cpp
  alica_engine/src/engine/IRoleAssignment.cpp
  alica_engine/src/engine/Logger.cpp
  alica_engine/src/engine/PlanBase.cpp
  alica_engine/src/engine/RuleBook.cpp
  alica_engine/src/engine/RunnableObject.cpp
  alica_engine/src/engine/RunningPlan.cpp
  alica_engine/src/engine/StaticRoleAssignment.cpp
  alica_engine/src/engine/TeamObserver.cpp
  alica_engine/src/engine/UtilityFunction.cpp
  alica_engine/src/engine/allocationauthority/AuthorityManager.cpp
  alica_engine/src/engine/allocationauthority/CycleManager.cpp
  alica_engine/src/engine/modelmanagement/ModelManager.cpp
  alica_engine/src/engine/modelmanagement/factories/Factory.cpp
  alica_engine/src/engine/modelmanagement/factories/QuantifierFactory.cpp
  alica_engine/src/engine/planselector/PlanSelector.cpp
  alica_engine/src/engine/planselector/TaskAssignmentProblem.cpp
  alica_engine/src/engine/teammanager/TeamManager.cpp
  supplementary/alica_ros1/alica_ros_turtlesim/Expr/src/GoTo.cpp
  supplementary/alica_ros1/alica_ros_turtlesim/alica_turtlesim_library/include/CircleRuntimeCondition.h
  supplementary/alica_ros1/alica_ros_turtlesim/alica_turtlesim_library/src/CircleRuntimeCondition.cpp
  supplementary/alica_ros1/alica_ros_turtlesim/alica_turtlesim_library/src/Go2RandomPosition.cpp
  supplementary/alica_ros1/alica_ros_turtlesim/alica_turtlesim_library/src/GoTo.cpp
  supplementary/alica_ros1/alica_ros_turtlesim/alica_turtlesim_library/src/Master.cpp
  supplementary/alica_ros1/alica_ros_turtlesim/alica_turtlesim_library/src/Move.cpp
  supplementary/alica_ros1/alica_ros_turtlesim/alica_turtlesim_library/src/conditions.cpp
  supplementary/alica_ros1/alica_ros_turtlesim/etc/Alica.yaml
  supplementary/alica_ros1/alica_ros_turtlesim/src/base.cpp
  supplementary/alica_ros1/supplementary_tests/src/test/test_alica_dynamicloadcreator.cpp
  supplementary/alica_tracing/include/tracing/TraceFactory.h
  supplementary/alica_tracing/src/tracing/TraceFactory.cpp
Labels: Improved

#387 Cleanup for unused functions
  alica_engine/include/engine/model/Plan.h
  alica_engine/include/engine/model/PlanType.h
  alica_engine/include/engine/model/State.h
  alica_engine/include/engine/model/VariableBinding.h
  alica_engine/src/engine/model/Behaviour.cpp
  alica_engine/src/engine/model/Plan.cpp
  alica_engine/src/engine/model/PlanType.cpp
  alica_engine/src/engine/model/State.cpp
  alica_engine/src/engine/model/VariableBinding.cpp
  alica_engine/src/engine/modelmanagement/factories/PlanTypeFactory.cpp
Labels: Refactored

#391 Check plan hash while checking for duplicate agent
  alica_engine/src/engine/teammanager/TeamManager.cpp
Labels: No changelog

#392 Add agent id, agent name to global blackboard
  alica_engine/include/engine/AlicaContext.h
  alica_engine/src/engine/AlicaContext.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_alica_init_shutdown.cpp
Labels: Improved

#393 Update codegen jars
  supplementary/alica_codegeneration/codegen/PlanDesignerFX-Codegeneration-0.1.1.1422.jar
  supplementary/alica_codegeneration/codegen/PlanDesignerFX-Codegeneration-0.1.1.1447.jar
  supplementary/alica_codegeneration/codegen/plugins/alica-plan-designer-fx-default-plugin-0.1.1-SNAPSHOT.jar
Labels: Fixed

#388 Fixes to properly free allocated memory at shutdown
  alica_dummy_proxy/src/communication/AlicaDummyCommunication.cpp
  alica_engine/include/engine/AlicaContext.h
  alica_engine/include/engine/AlicaEngine.h
  alica_engine/include/engine/PlanBase.h
  alica_engine/include/engine/RuntimeBehaviourFactory.h
  alica_engine/include/engine/RuntimePlanFactory.h
  alica_engine/include/engine/modelmanagement/ModelManager.h
  alica_engine/include/engine/modelmanagement/factories/VariableFactory.h
  alica_engine/src/engine/AlicaContext.cpp
  alica_engine/src/engine/AlicaEngine.cpp
  alica_engine/src/engine/PlanBase.cpp
  alica_engine/src/engine/RunningPlan.cpp
  alica_engine/src/engine/RuntimeBehaviourFactory.cpp
  alica_engine/src/engine/RuntimePlanFactory.cpp
  alica_engine/src/engine/modelmanagement/ModelManager.cpp
  alica_engine/src/engine/modelmanagement/factories/Factory.cpp
  alica_engine/src/engine/modelmanagement/factories/VariableFactory.cpp
  alica_engine/src/engine/syncmodule/SyncModule.cpp
  supplementary/alica_ros1/alica_tests/include/test_alica.h
  supplementary/alica_ros1/alica_tests/src/test/test_assignment.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_config_change.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_task_assignment.cpp
Labels: Fixed

#394 Fix SyncStopTimerRosImpl member init order
  supplementary/alica_ros1/alica_ros_proxy/include/clock/AlicaRosTimer.h
Labels: Fixed
