Repository rapyuta-robotics/alica, pull requests merged in 2023-02, with the labels that each got.

#396 Fix problems spotted by clang
  alica_engine/include/engine/IAlicaCommunication.h
  alica_engine/include/engine/IBehaviourCreator.h
  alica_engine/include/engine/IConditionCreator.h
  alica_engine/include/engine/IPlanCreator.h
  alica_engine/include/engine/ITransitionConditionCreator.h
  alica_engine/include/engine/Output.h
  alica_engine/include/engine/TeamObserver.h
  alica_engine/include/engine/collections/RobotProperties.h
  alica_engine/include/engine/expressionhandler/ExpressionHandler.h
  alica_engine/include/engine/logging/Logging.h
  alica_engine/include/engine/syncmodule/SynchronisationProcess.h
  alica_engine/src/engine/collections/RobotProperties.cpp
  alica_engine/src/engine/constraintmodul/ConditionStore.cpp
  alica_engine/src/engine/constraintmodul/VariableSyncModule.cpp
  alica_engine/src/engine/modelmanagement/factories/BehaviourFactory.cpp
  alica_engine/src/engine/modelmanagement/factories/PlanFactory.cpp
  alica_engine/src/engine/modelmanagement/factories/QuantifierFactory.cpp
  alica_engine/src/engine/modelmanagement/factories/TransitionConditionFactory.cpp
  alica_engine/src/engine/planselector/TaskAssignmentProblem.cpp
  alica_engine/src/engine/syncmodule/SynchronisationProcess.cpp
  alica_engine/src/engine/teammanager/Agent.cpp
  alica_engine/src/engine/teammanager/TeamManager.cpp
  supplementary/alica_ros1/alica_ros_proxy/include/communication/AlicaRosCommunication.h
  supplementary/alica_ros1/supplementary_tests/alica_supplementary_test_library/include/AcmeRuntimeCondition.h
  supplementary/autodiff/include/autodiff/Exp.h
  supplementary/constraintsolver/include/intervals/DownwardPropagator.h
  supplementary/constraintsolver/include/intervals/UpwardPropagator.h
  supplementary/constraintsolver/src/intervals/DownwardPropagator.cpp
  supplementary/constraintsolver/src/intervals/IntervalPropagator.cpp
  supplementary/constraintsolver/src/intervals/UpwardPropagator.cpp
  supplementary/constraintsolver/test/test_cnsmtgsolver.cpp
Labels: No changelog

#398 Remove engine references from constraintsolver
  alica_engine/include/engine/AlicaContext.h
  alica_engine/include/engine/constraintmodul/ISolver.h
  alica_engine/src/engine/AlicaContext.cpp
  alica_simple_solver/include/alica/reasoner/SimpleSolver.h
  alica_simple_solver/src/SimpleSolver.cpp
  supplementary/alica_ros1/alica_ros_turtlesim/src/base.cpp
  supplementary/alica_ros1/alica_tests/include/alica_tests/ConstraintTestPlanDummySolver.h
  supplementary/alica_ros1/alica_tests/src/ConstraintTestPlanDummySolver.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_alica_condition_plan.cpp
  supplementary/alica_ros1/supplementary_tests/include/test_supplementary.h
  supplementary/alica_ros1/supplementary_tests/src/test/Expr/include/ConstraintTestPlanDummySolver.h
  supplementary/alica_ros1/supplementary_tests/src/test/Expr/src/ConstraintTestPlanDummySolver.cpp
  supplementary/alica_ros1/supplementary_tests/src/test/test_alica_dynamicloadcreator.cpp
  supplementary/alica_ros1/supplementary_tests/src/test/test_variable_handling.cpp
  supplementary/alica_ros2/alica_ros2_turtlesim/src/base.cpp
  supplementary/constraintsolver/include/constraintsolver/CGSolver.h
  supplementary/constraintsolver/src/CGSolver.cpp
Labels: Refactored

#399 Fix simulation blackboard key access
  supplementary/alica_ros1/alica_ros_turtlesim/etc/plans/Simulation.pml
Labels: Fixed

#401 Add simulation plan details to turtlesim readme
  supplementary/alica_ros1/alica_ros_turtlesim/README.md
  supplementary/alica_ros1/alica_ros_turtlesim/doc/Simulation.png
  supplementary/alica_ros1/alica_ros_turtlesim/doc/blackboard_setup.png
Labels: No changelog

#400 Thread sanitizer fixes
  alica_dummy_proxy/CMakeLists.txt
  alica_dummy_proxy/include/communication/AlicaDummyCommunication.h
  alica_dummy_proxy/src/communication/AlicaDummyCommunication.cpp
  alica_engine/include/engine/Logger.h
  alica_engine/include/engine/PlanBase.h
  alica_engine/include/engine/RunningPlan.h
  alica_engine/include/engine/constraintmodul/VariableSyncModule.h
  alica_engine/include/engine/planselector/PlanSelector.h
  alica_engine/include/engine/teammanager/Agent.h
  alica_engine/include/engine/teammanager/TeamManager.h
  alica_engine/src/engine/Logger.cpp
  alica_engine/src/engine/PlanBase.cpp
  alica_engine/src/engine/constraintmodul/VariableSyncModule.cpp
  alica_engine/src/engine/teammanager/Agent.cpp
  alica_engine/src/engine/teammanager/TeamManager.cpp
  supplementary/alica_ros1/alica_tests/include/test_alica.h
Labels: Fixed

#404 Fix Alica blackboard and tracing initialization order
  alica_engine/src/engine/RunnableObject.cpp
Labels: Fixed

#403 Eliminate codegen from behaviors in supplementary tests
  supplementary/alica_ros1/supplementary_tests/src/test/Expr/include/supplementary_tests/DomainBehaviour.h
  supplementary/alica_ros1/supplementary_tests/src/test/Expr/include/supplementary_tests/GSolver/SolverTestBehaviour.h
  supplementary/alica_ros1/supplementary_tests/src/test/Expr/include/supplementary_tests/GSolver/SolverTestBehaviour1417424455986.h
  supplementary/alica_ros1/supplementary_tests/src/test/Expr/include/supplementary_tests/ProblemModule/QueryBehaviour1.h
  supplementary/alica_ros1/supplementary_tests/src/test/Expr/include/supplementary_tests/ProblemModule/QueryBehaviour11479556104511.h
  supplementary/alica_ros1/supplementary_tests/src/test/Expr/src/ConditionCreator.cpp
  supplementary/alica_ros1/supplementary_tests/src/test/Expr/src/DomainBehaviour.cpp
  supplementary/alica_ros1/supplementary_tests/src/test/Expr/src/GSolver/SolverTestBehaviour.cpp
  supplementary/alica_ros1/supplementary_tests/src/test/Expr/src/GSolver/SolverTestBehaviour1417424455986.cpp
  supplementary/alica_ros1/supplementary_tests/src/test/Expr/src/ProblemModule/QueryBehaviour1.cpp
  supplementary/alica_ros1/supplementary_tests/src/test/Expr/src/ProblemModule/QueryBehaviour11479556104511.cpp
Labels: Refactored

#406 Remove access to deprecated default value
  alica_engine/include/engine/blackboard/BlackboardBlueprint.h
  alica_engine/src/engine/modelmanagement/factories/BlackboardBlueprintFactory.cpp
Labels: Fixed

#405 Log improvements
  alica_dynamic_loading/src/DynamicBehaviourCreator.cpp
  alica_dynamic_loading/src/DynamicConditionCreator.cpp
  alica_dynamic_loading/src/DynamicConstraintCreator.cpp
  alica_dynamic_loading/src/DynamicPlanCreator.cpp
  alica_dynamic_loading/src/DynamicTransitionConditionCreator.cpp
  supplementary/alica_ros1/alica_ros_proxy/src/logger/AlicaRosLogger.cpp
Labels: Improved

#412 Fix for tests
  supplementary/alica_ros1/alica_tests/include/test_alica.h
  supplementary/alica_ros1/alica_tests/src/test/test_adjacent_plans_success.cpp
Labels: Fixed

#413 Dont use raw ptr for nodehandle
  supplementary/alica_ros1/alica_ros_proxy/include/communication/AlicaRosCommunication.h
  supplementary/alica_ros1/alica_ros_proxy/src/communication/AlicaRosCommunication.cpp
Labels: Improved

#418 Revert timing value change in test
  supplementary/alica_ros1/alica_tests/src/test/test_adjacent_plans_success.cpp
Labels: No changelog

#414 Remove unused code about idle tasks
  alica_engine/include/engine/modelmanagement/ModelManager.h
  alica_engine/include/engine/modelmanagement/factories/EntryPointFactory.h
  alica_engine/include/engine/modelmanagement/factories/Factory.h
  alica_engine/include/engine/planselector/PartialAssignmentPool.h
  alica_engine/src/engine/model/EntryPoint.cpp
  alica_engine/src/engine/model/Task.cpp
  alica_engine/src/engine/modelmanagement/factories/EntryPointFactory.cpp
  alica_engine/src/engine/modelmanagement/factories/Factory.cpp
  alica_engine/src/engine/planselector/PartialAssignmentPool.cpp
Labels: No changelog

#421 Transition fixes for tests
  supplementary/alica_ros1/alica_tests/include/alica_tests/TestWorldModel.h
  supplementary/alica_ros1/alica_tests/src/TestWorldModel.cpp
Labels: Fixed

#416 Remove precompiler stuff for c++11
  alica_engine/include/engine/AlicaContext.h
  alica_engine/include/engine/logging/AlicaLogger.h
Labels: Deprecated

#417 alica_ros_turtlesim fixed for more than (core number * 2) robots
  supplementary/alica_ros1/alica_ros_turtlesim/libalica-turtlesim/src/GoTo.cpp
Labels: Fixed

#415 Remove model manager ref from team manager
  alica_engine/include/engine/collections/RobotEngineData.h
  alica_engine/include/engine/teammanager/Agent.h
  alica_engine/include/engine/teammanager/TeamManager.h
  alica_engine/src/engine/AlicaEngine.cpp
  alica_engine/src/engine/collections/RobotEngineData.cpp
  alica_engine/src/engine/teammanager/Agent.cpp
  alica_engine/src/engine/teammanager/TeamManager.cpp
Labels: Deprecated

#422 Removing defaultValue
  alica_engine/include/engine/blackboard/Blackboard.h
  alica_engine/include/engine/blackboard/BlackboardBlueprint.h
  alica_engine/include/engine/modelmanagement/Strings.h
  supplementary/alica_ros1/alica_ros_turtlesim/etc/plans/Simulation.pml
  supplementary/alica_ros1/alica_ros_turtlesim/etc/plans/behaviours/WaitForTrigger.beh
  supplementary/alica_ros1/alica_tests/src/test/test_blackboard.cpp
Labels: Deprecated

#427 Remove references to nonexistent modelfactory
  alica_engine/include/engine/PlanRepository.h
  alica_engine/include/engine/model/AbstractPlan.h
  alica_engine/include/engine/model/AlicaElement.h
  alica_engine/include/engine/model/Behaviour.h
  alica_engine/include/engine/model/Condition.h
  alica_engine/include/engine/model/Plan.h
  alica_engine/include/engine/model/PlanType.h
  alica_engine/include/engine/model/PreCondition.h
  alica_engine/include/engine/model/Quantifier.h
  alica_engine/include/engine/model/Role.h
  alica_engine/include/engine/model/RoleSet.h
  alica_engine/include/engine/model/State.h
  alica_engine/include/engine/model/Synchronisation.h
  alica_engine/include/engine/model/Task.h
  alica_engine/include/engine/model/TaskRepository.h
  alica_engine/include/engine/model/TerminalState.h
  alica_engine/include/engine/model/Transition.h
  alica_engine/include/engine/model/TransitionCondition.h
  alica_engine/include/engine/model/TransitionConditionRepository.h
  alica_engine/include/engine/model/Variable.h
  alica_engine/include/engine/model/VariableBinding.h
  alica_engine/src/engine/model/Quantifier.cpp
Labels: Deprecated

#426 Cleanup
  alica_dummy_proxy/src/communication/AlicaDummyCommunication.cpp
  alica_engine/src/engine/syncmodule/SynchronisationProcess.cpp
  supplementary/alica_ros1/alica_ros_proxy/include/logger/AlicaRosLogger.h
  supplementary/alica_ros1/alica_ros_proxy/src/communication/AlicaRosCommunication.cpp
  supplementary/alica_ros1/alica_ros_proxy/src/logger/AlicaRosLogger.cpp
  supplementary/alica_ros1/alica_ros_turtlesim/src/base.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_success.cpp
  supplementary/alica_ros2/alica_ros2_proxy/src/ros2_communication/AlicaRosCommunication.cpp
Labels: No changelog

#423 Fix Alica tracing chars string value handling
  alica_engine/include/engine/IAlicaTrace.h
Labels: Fixed

#424 Remove friends from Task
  alica_engine/include/engine/model/EntryPoint.h
  alica_engine/include/engine/model/Task.h
  alica_engine/src/engine/UtilityFunction.cpp
  alica_engine/src/engine/model/Task.cpp
  alica_engine/src/engine/modelmanagement/factories/TaskFactory.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_alica_authority.cpp
Labels: No changelog

#431 Fix for warnings
  alica_engine/include/engine/AlicaContext.h
  alica_engine/include/engine/RunnableObject.h
  alica_engine/include/engine/RunningPlan.h
Labels: No changelog

#430 Clean up debug logs
  alica_engine/src/engine/RuleBook.cpp
  alica_engine/src/engine/TeamObserver.cpp
Labels: Fixed

#428 removing Configuration
  alica_engine/CMakeLists.txt
  alica_engine/include/engine/PlanBase.h
  alica_engine/include/engine/PlanRepository.h
  alica_engine/include/engine/RunningPlan.h
  alica_engine/include/engine/model/Configuration.h
  alica_engine/include/engine/modelmanagement/factories/ConfigurationFactory.h
  alica_engine/include/engine/planselector/PlanSelector.h
  alica_engine/src/engine/BasicBehaviour.cpp
  alica_engine/src/engine/PlanBase.cpp
  alica_engine/src/engine/RuleBook.cpp
  alica_engine/src/engine/RunningPlan.cpp
  alica_engine/src/engine/model/Configuration.cpp
  alica_engine/src/engine/modelmanagement/ModelManager.cpp
  alica_engine/src/engine/modelmanagement/factories/ConfigurationFactory.cpp
  alica_engine/src/engine/modelmanagement/factories/Factory.cpp
  alica_engine/src/engine/planselector/PlanSelector.cpp
  alica_test_utility/src/TestContext.cpp
  alica_test_utility/src/Util.cpp
  supplementary/alica_ros1/alica_tests/libalica-tests/src/libalica-tests/behaviours/ReadConfigurationBehaviour.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/include/alica_tests/conditions/conditions.h
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/TransitionConditionCreator.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/conditions/conditions.cpp
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/ReadConfInPlantype.pml
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/ReadConfigurationPlan.pml
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/ReadConfigurationPlantype.pty
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/conditions/ConditionRepository.cnd
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/configurations/ConfigA.cfg
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/configurations/ConfigB.cfg
  supplementary/alica_ros1/alica_tests/src/test/test_task_assignment.cpp
Labels: Deprecated

#434 Revert "removing Configuration"
  alica_engine/CMakeLists.txt
  alica_engine/include/engine/PlanBase.h
  alica_engine/include/engine/PlanRepository.h
  alica_engine/include/engine/RunningPlan.h
  alica_engine/include/engine/model/Configuration.h
  alica_engine/include/engine/modelmanagement/factories/ConfigurationFactory.h
  alica_engine/include/engine/planselector/PlanSelector.h
  alica_engine/src/engine/BasicBehaviour.cpp
  alica_engine/src/engine/PlanBase.cpp
  alica_engine/src/engine/RuleBook.cpp
  alica_engine/src/engine/RunningPlan.cpp
  alica_engine/src/engine/model/Configuration.cpp
  alica_engine/src/engine/modelmanagement/ModelManager.cpp
  alica_engine/src/engine/modelmanagement/factories/ConfigurationFactory.cpp
  alica_engine/src/engine/modelmanagement/factories/Factory.cpp
  alica_engine/src/engine/planselector/PlanSelector.cpp
  alica_test_utility/src/TestContext.cpp
  alica_test_utility/src/Util.cpp
  supplementary/alica_ros1/alica_tests/libalica-tests/src/libalica-tests/behaviours/ReadConfigurationBehaviour.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/include/alica_tests/conditions/conditions.h
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/TransitionConditionCreator.cpp
  supplementary/alica_ros1/alica_tests/src/test/Expr/src/conditions/conditions.cpp
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/ReadConfInPlantype.pml
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/ReadConfigurationPlan.pml
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/ReadConfigurationPlantype.pty
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/conditions/ConditionRepository.cnd
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/configurations/ConfigA.cfg
  supplementary/alica_ros1/alica_tests/src/test/etc/plans/configurations/ConfigB.cfg
  supplementary/alica_ros1/alica_tests/src/test/test_task_assignment.cpp
Labels: Fixed

#433 Minor engine improvements
  alica_engine/include/engine/BasicBehaviour.h
  alica_engine/include/engine/BasicPlan.h
  alica_engine/include/engine/BasicUtilityFunction.h
  alica_engine/include/engine/blackboard/BlackboardBlueprint.h
  alica_engine/src/engine/BasicBehaviour.cpp
  alica_engine/src/engine/BasicPlan.cpp
  alica_engine/src/engine/BasicUtilityFunction.cpp
  alica_engine/src/engine/modelmanagement/factories/PlanFactory.cpp
Labels: Improved

#436 Undo API breaking change
  supplementary/alica_ros1/alica_ros_proxy/include/logger/AlicaRosLogger.h
Labels: Fixed

#435 Remove deprecated docs
  docs/deprecated_doc/BehCode.md
Labels: Deprecated

#437 README.md link fix
  README.md
Labels: No changelog

#361 Remove ROS from Alica Tests
  alica_engine/CMakeLists.txt
  alica_engine/include/engine/AlicaTimer.h
  alica_engine/src/engine/AlicaTimer.cpp
  supplementary/alica_ros1/alica_tests/CMakeLists.txt
  supplementary/alica_ros1/alica_tests/alica_testsConfig.cmake.in
  supplementary/alica_ros1/alica_tests/include/test_alica.h
  supplementary/alica_ros1/alica_tests/package.xml
  supplementary/alica_ros1/alica_tests/src/test/test_agent_dies.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_agent_discovery.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_alica_authority.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_alica_logger.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_alica_multi_agent_plan.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_alica_scheduling.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_alica_sync_transition.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_alica_tracing.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_assignment.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_config_change.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_failure_handling.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_main.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_success.cpp
  supplementary/alica_ros1/alica_tests/src/test/test_yaml_cfg.cpp
Labels: Refactored

#438 Simplify log namespacing
  .github/workflows/main.yml
  supplementary/alica_ros1/alica_ros_proxy/src/logger/AlicaRosLogger.cpp
Labels: Fixed
