Repository rapyuta-robotics/alica, pull requests merged in 2023-05, with the labels that each got.

#493 Ignore unknown agents
  alica_engine/src/engine/model/ForallAgents.cpp
Labels: Fixed

#494 Remove eventDriven & deferring of behaviours
  alica_engine/include/engine/BasicBehaviour.h
  alica_engine/include/engine/model/Behaviour.h
  alica_engine/include/engine/modelmanagement/Strings.h
  alica_engine/src/engine/BasicBehaviour.cpp
  alica_engine/src/engine/model/Behaviour.cpp
  alica_engine/src/engine/modelmanagement/factories/BehaviourFactory.cpp
  alica_test_utility/include/alica/test/TestContext.h
  alica_test_utility/src/TestContext.cpp
  alica_tests/CMakeLists.txt
  alica_tests/src/test/test_alica_behaviourtrigger.cpp
Labels: Deprecated

#495 Replace world model test with global bb test
  alica_tests/CMakeLists.txt
  alica_tests/src/test/test_alica_engine_worldmodel.cpp
  alica_tests/src/test/test_blackboard.cpp
Labels: Refactored

#496 Logging fixes
  alica_engine/include/engine/AlicaContext.h
  alica_engine/include/engine/logging/AlicaLogger.h
  alica_engine/src/engine/AlicaContext.cpp
  alica_engine/src/engine/logging/AlicaDefaultLogger.cpp
  alica_engine/src/engine/logging/AlicaLogger.cpp
  alica_tests/include/test_alica.h
  alica_tests/src/test/test_alica_logger.cpp
  supplementary/alica_ros1/supplementary_tests/src/test/test_alica_dynamicloadcreator.cpp
Labels: Fixed

#500 Log once instead of throwing
  alica_engine/src/engine/AlicaContext.cpp
Labels: Improved
